---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


'''{r cache=FALSE}
knitr::read_chunk('data_analysis.R')
'''

```{Showing Data}
```




```{r install packages}
install.packages("gtrendsR")
install.packages("lubridate")
```

```{r load the gtrendsR package}
library(gtrendsR)
```


```{r load the lubridate package}
library(lubridate)
```

```{r google trends query}
df <- gtrends(keyword = c("lose weight"),geo=c("GR"),time="2016-12-01 2018-12-31")
df <- gtrends(keyword = c("lose weight"),geo=c("GR"),time="2016-12-01 2018-12-31")
df_iot <- df$interest_over_time
winter <- df_iot[month(df_iot$date) == 12 |month(df_iot$date) == 1 |month(df_iot$date) == 2, ]
summer <- df_iot[month(df_iot$date) == 6 |month(df_iot$date) == 7 |month(df_iot$date) == 8, ]
trends <- gtrendsR::gtrends(keyword = c("lose weight"),geo = c("GR"),time = "2016-12-01 2018-12-31")
```

```{r get interest overtime}
interest_over_time <- trends$interest_over_time
```


```{r save data}
my_data <- gtrends(keyword = c("lose weight"), geo = c("GR"), time = "2016-12-01 2018-12-31")
write.csv(my_data$interest_over_time,"interestovertime.csv")
```


```{r used of Kolmogorov-Smirnov test}
ks.test(x = df_wide$group_a, y = df_wide$group_b)
```


```{r used independent t-test to analyse data}
t.test(x = df_wide$group_a, y = df_wide$group_b, var.equal = TRUE)
```


